server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://v.qq.com/
          predicates:
            - Query=url,v

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

